name: Deploy to Firebase Hosting on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_deploy:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl unzip xz-utils

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.4"
          channel: stable
          cache: false

      - name: Verify Flutter installation
        run: |
          echo "üîç Verificando instalaci√≥n de Flutter..."
          which flutter || echo "‚ö†Ô∏è Flutter no encontrado en PATH"
          flutter --version || echo "‚ö†Ô∏è No se pudo ejecutar 'flutter --version'"
          flutter doctor

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web

      - name: Debug Environment Variables
        run: env | sort  # Verifica si la variable de Firebase est√° presente

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --debug
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SCANNER_6C414 }}

      - name: Post-Job Debugging (Antes de Cleanup)
        if: always()
        run: |
          echo "üõ†Ô∏è Limpieza final..."
          ls -lah $RUNNER_TEMP || echo "‚ö†Ô∏è No se encontr√≥ la carpeta temporal"
          ls -lah $HOME || echo "‚ö†Ô∏è No se encontr√≥ el home"
